### ISSUE TITLE
Validación password, ingresarUsuario

### ISSUE THREAD

**Issue by aitrusgit** [yoLUkAsss/rentauto#5]
Este chequeo

``` xtend
        if(!user.passValida(password) || !user.validez){
            throw new IngresoNoValidoException
        }
```

Podría se delegado por completo en Usuario

``` xtend
              user.validarIngreso(password);
```

**Comment by aitrusgit** [comment]
Igual en `cambiarPassword`. Les propongo que refactoricen ese método para que:
1- use el `validarIngreso` que les sugerí antes
2- el cambio de password + el chequeo de password vieja contra nueva sea parte de otro método de _Usuario_

**Comment by Ramshell** [comment]
no hay problema de cohesiono semantico si usuario conoce IngresoNoValidoException?

el cambio que hice fue hacer una funcion que un usuario con su password, me dice si es valido con un booleano. Simplemente por lo de la pregunta de arriba.

**Comment by aitrusgit** [comment]
Ni.
Depende de las responsabilidades que asignes a tu Usuario. En este modelo que tenemos hasta ahora el Usuario es una abstracción del usuario y sus credenciales que le permiten ganar accesso al sistema. No veo mal que sea el Usuario quien controle y tire excepción de acceso invalido cuando se le pide controlar el acceso.

Si, se puede pensar de forma un poco más génerica. Algo como:

``` xtend
# Usuario
def validarPassword(password) throws PaswordInvalidoException
```

La cual en el servicio podrían catchear y wrappear en una AccessoInvalidoException. Aunque honestamente no veo la ganancia en ello (AccesoInvalidoException me parece lo suficientemente abstracta)

**Comment by aitrusgit** [comment]
Si lo que molesta es que el Usuario tenga responsabilidades relativas a su acceso y manejo de crendenciales... puede ser porque estamos acostumbrados a que el Usuario sea una figura distinta dentro del modelo de los sistemas. 

Por ejemplo, que el usuario tenga reservas de autos y cosas así

Todavía no estamos ahí, por ahora el usuario es solo manejo de acceso. Si eso llega a cambiar siempre es posible refactorizar. Un modelo que me gusta es el de:

![UML](http://yuml.me/8c2f5bbe)

Pero lo que siempre apoyamos a la hora de diseñar es ser iterativos e incrementales. Para esta iteración puntual estamos bien con el diseño original.
